services:
  web:
    image: jmprof/boardlog:latest
    ports:
      - "8080:80"
    environment:
      - APP_URL=http://localhost:8080
      - DB_HOST=db
      - DB_NAME=boardlog
      - DB_USER=boardlog
      - DB_PASS=boardlog
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: boardlog
      MYSQL_USER: boardlog
      MYSQL_PASSWORD: boardlog
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
